---
title: "Relationship between predicted and actual price change between periods t-1 and t"
author: "(Without emotions)"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
---


$P_{t}-P_{t-1} = \alpha + \beta(B_{t}^t-P_{t-1})$

# All sessions – combined {.tabset}

## All subjects
```{r, echo= FALSE, message=FALSE, warning=FALSE}
library(plm)
library(tidyverse)
library(jtools)
library(huxtable)
library(ggplot2)
library(ggpubr)

mydata <- read.csv(file="C:/Users/Liran/Google Drive/Study/PhD/Face_Reader/The_Experiment/AER_table5_price_change/S1_S6_transpose.csv", header=TRUE, sep=",")

market1 = subset(mydata,to_run_1==1)
market2 = subset(mydata,to_run_1==1)
market1 = subset(market1, period<=15)
market2 = subset(market2, period>15)
#OLS market 1
OLS1 = lm(delta_price ~ belief_minus_price_t_minus_1, data=market1)
#OLS market 2
OLS2 = lm(delta_price ~ belief_minus_price_t_minus_1, data=market2)

export_summs(OLS1, OLS2, digits = 4,
             model.names = c("Market1","Market2"),
             statistics = c(N = "nobs", Adj_R2 = "adj.r.squared", R2 = "r.squared") ,
            coefs =  c("Intercept" = "(Intercept)","X" = "belief_minus_price_t_minus_1"),
             error_format = "({p.value})", stars = c(`***` = 0.01, `**` = 0.05, `*` = 0.1))
plot1 = ggplot(market1, aes(x=belief_minus_price_t_minus_1, y=delta_price))+
  geom_point(shape = 21,color = "blue", size = 2) + 
  geom_hline(yintercept=0, linetype="dashed", color = "red", size=1) + 
  geom_vline(xintercept = 0, linetype="dashed", color = "red", size=1)+
  scale_x_continuous(name="B-P", limits=c(-46, 127)) +
  scale_y_continuous(name="P-P", limits=c(-249, 81))


plot2 = ggplot(market2, aes(x=belief_minus_price_t_minus_1, y=delta_price))+
  geom_point(shape = 21,color = "blue", size = 2) + 
  geom_hline(yintercept=0, linetype="dashed", color = "red", size=1) + 
  geom_vline(xintercept = 0, linetype="dashed", color = "red", size=1)+
  scale_x_continuous(name="B-P", limits=c(-46, 127))+
  scale_y_continuous(name="P-P", limits=c(-249, 81))

ggarrange(plot1, plot2, 
          labels = c("Market 1", "Market 2"),
          ncol = 2, nrow = 1)
```


## Traders only
```{r, echo= FALSE, message=FALSE, warning=FALSE}



#OLS market 1
OLS1 = lm(delta_price ~ belief_minus_price_t_minus_1_traders, data=market1)
#OLS market 2
OLS2 = lm(delta_price ~ belief_minus_price_t_minus_1_traders, data=market2)

export_summs(OLS1, OLS2, digits = 4,
             model.names = c("Market1","Market2"),
             statistics = c(N = "nobs", Adj_R2 = "adj.r.squared", R2 = "r.squared") ,
            coefs =  c("Intercept" = "(Intercept)","X" = "belief_minus_price_t_minus_1_traders"),
             error_format = "({p.value})", stars = c(`***` = 0.01, `**` = 0.05, `*` = 0.1))
plot1 = ggplot(market1, aes(x=belief_minus_price_t_minus_1_traders, y=delta_price))+
  geom_point(shape = 21,color = "blue", size = 2) + 
  geom_hline(yintercept=0, linetype="dashed", color = "red", size=1) + 
  geom_vline(xintercept = 0, linetype="dashed", color = "red", size=1)+
  scale_x_continuous(name="B-P", limits=c(-46, 127)) +
  scale_y_continuous(name="P-P", limits=c(-249, 81))


plot2 = ggplot(market2, aes(x=belief_minus_price_t_minus_1_traders, y=delta_price))+
  geom_point(shape = 21,color = "blue", size = 2) + 
  geom_hline(yintercept=0, linetype="dashed", color = "red", size=1) + 
  geom_vline(xintercept = 0, linetype="dashed", color = "red", size=1)+
  scale_x_continuous(name="B-P", limits=c(-46, 127))+
  scale_y_continuous(name="P-P", limits=c(-249, 81))

ggarrange(plot1, plot2, 
          labels = c("Market 1", "Market 2"),
          ncol = 2, nrow = 1)
```


## Observers only
```{r, echo= FALSE, message=FALSE, warning=FALSE}

#OLS market 1
OLS1 = lm(delta_price ~ belief_minus_price_t_minus_1_obs, data=market1)
#OLS market 2
OLS2 = lm(delta_price ~ belief_minus_price_t_minus_1_obs, data=market2)

export_summs(OLS1, OLS2, digits = 4,
             model.names = c("Market1","Market2"),
             statistics = c(N = "nobs", Adj_R2 = "adj.r.squared", R2 = "r.squared") ,
            coefs =  c("Intercept" = "(Intercept)","X" = "belief_minus_price_t_minus_1_obs"),
             error_format = "({p.value})", stars = c(`***` = 0.01, `**` = 0.05, `*` = 0.1))
plot1 = ggplot(market1, aes(x=belief_minus_price_t_minus_1_obs, y=delta_price))+
  geom_point(shape = 21,color = "blue", size = 2) + 
  geom_hline(yintercept=0, linetype="dashed", color = "red", size=1) + 
  geom_vline(xintercept = 0, linetype="dashed", color = "red", size=1)+
  scale_x_continuous(name="B-P", limits=c(-46, 127)) +
  scale_y_continuous(name="P-P", limits=c(-249, 81))


plot2 = ggplot(market2, aes(x=belief_minus_price_t_minus_1_obs, y=delta_price))+
  geom_point(shape = 21,color = "blue", size = 2) + 
  geom_hline(yintercept=0, linetype="dashed", color = "red", size=1) + 
  geom_vline(xintercept = 0, linetype="dashed", color = "red", size=1)+
  scale_x_continuous(name="B-P", limits=c(-46, 127))+
  scale_y_continuous(name="P-P", limits=c(-249, 81))

ggarrange(plot1, plot2, 
          labels = c("Market 1", "Market 2"),
          ncol = 2, nrow = 1)
```

