---
title: "Emotions Summary"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
    theme: cosmo
    highlight: textmate
---

# All sessions

## Emotions Mean and S.D
Mean and standard deviation of emotions across subjects and 10-s interbals (in the belief stage)
```{r, echo= FALSE, message=FALSE, warning=FALSE}
library(knitr)



mydata <- read.csv(file="C:/Users/Liran/Google Drive/Study/PhD/Face_Reader/The_Experiment/Emotional_state_summery/emotional_progression_beliefs.csv", header=TRUE, sep=",")

emotions_progression = mydata

average_all =c()
average_all$Neutral = mean(emotions_progression$neutral , na.rm = TRUE)
average_all$Happy = mean(emotions_progression$happy , na.rm = TRUE)
average_all$Sad = mean(emotions_progression$sad , na.rm = TRUE)
average_all$Angry = mean(emotions_progression$angry , na.rm = TRUE)
average_all$Surprised = mean(emotions_progression$surprised , na.rm = TRUE)
average_all$Scared = mean(emotions_progression$scared , na.rm = TRUE)
average_all$Disgusted = mean(emotions_progression$disgusted , na.rm = TRUE)
average_all$Valence = mean(emotions_progression$valence , na.rm = TRUE)
average_all = as.data.frame(average_all)

emotions_progression_traders = subset(emotions_progression, traders_1==1)
average_traders = c()
average_traders$Neutral = mean(emotions_progression_traders$neutral , na.rm = TRUE)
average_traders$Happy = mean(emotions_progression_traders$happy , na.rm = TRUE)
average_traders$Sad = mean(emotions_progression_traders$sad , na.rm = TRUE)
average_traders$Angry = mean(emotions_progression_traders$angry , na.rm = TRUE)
average_traders$Surprised = mean(emotions_progression_traders$surprised , na.rm = TRUE)
average_traders$Scared = mean(emotions_progression_traders$scared , na.rm = TRUE)
average_traders$Disgusted = mean(emotions_progression_traders$disgusted , na.rm = TRUE)
average_traders$Valence = mean(emotions_progression_traders$valence , na.rm = TRUE)
average_traders = as.data.frame(average_traders)

emotions_progression_observers = subset(emotions_progression, traders_1==0)
average_observers = c()
average_observers$Neutral = mean(emotions_progression_observers$neutral , na.rm = TRUE)
average_observers$Happy = mean(emotions_progression_observers$happy , na.rm = TRUE)
average_observers$Sad = mean(emotions_progression_observers$sad , na.rm = TRUE)
average_observers$Angry = mean(emotions_progression_observers$angry , na.rm = TRUE)
average_observers$Surprised = mean(emotions_progression_observers$surprised , na.rm = TRUE)
average_observers$Scared = mean(emotions_progression_observers$scared , na.rm = TRUE)
average_observers$Disgusted = mean(emotions_progression_observers$disgusted , na.rm = TRUE)
average_observers$Valence = mean(emotions_progression_observers$valence , na.rm = TRUE)
average_observers = as.data.frame(average_observers)

traders_observers =data.frame()
traders_observers = rbind(traders_observers,average_all)
traders_observers = rbind(traders_observers,average_traders)
traders_observers = rbind(traders_observers,average_observers)

row.names(traders_observers) = c("All Participates","Traders", "Observers")
kable(traders_observers, caption = "Mean")

#SD
SD_all = apply(emotions_progression[,3:10],2,sd , na.rm = TRUE)
SD_traders = apply(emotions_progression_traders[,3:10],2,sd , na.rm = TRUE)
SD_observers = apply(emotions_progression_observers[,3:10],2,sd , na.rm = TRUE)

traders_observers =data.frame()
traders_observers = rbind(traders_observers,SD_all)
traders_observers = rbind(traders_observers,SD_traders)
traders_observers = rbind(traders_observers,SD_observers)
row.names(traders_observers) = c("All Participates","Traders", "Observers")
colnames(traders_observers) = c("Neutral", "Happy", "Sad" , "Angry" , "Surprised" , "Scared" , "Disgusted" ,"Valence")
kable(traders_observers, caption = "S.D")

#t.test
Neutral= t.test(emotions_progression_traders$neutral, emotions_progression_observers$neutral, alternative = "two.sided", var.equal = FALSE)
Happy= t.test(emotions_progression_traders$happy, emotions_progression_observers$happy, alternative = "two.sided", var.equal = FALSE)
Sad= t.test(emotions_progression_traders$sad, emotions_progression_observers$sad, alternative = "two.sided", var.equal = FALSE)
Angry= t.test(emotions_progression_traders$angry, emotions_progression_observers$angry, alternative = "two.sided", var.equal = FALSE)
Surprised= t.test(emotions_progression_traders$surprised, emotions_progression_observers$surprised, alternative = "two.sided", var.equal = FALSE)
Scared= t.test(emotions_progression_traders$scared, emotions_progression_observers$scared, alternative = "two.sided", var.equal = FALSE)
Disgusted= t.test(emotions_progression_traders$disgusted, emotions_progression_observers$disgusted, alternative = "two.sided", var.equal = FALSE)
Valence= t.test(emotions_progression_traders$valence, emotions_progression_observers$valence, alternative = "two.sided", var.equal = FALSE)


```

## Diffrence Between Traders and Observers Emotions
Unpaired Two-Samples T-test (two-tailed tests)
```{r, echo= FALSE, message=FALSE, warning=FALSE}
p_value =c()
p_value$Neutral = Neutral$p.value
p_value$Happy = Happy$p.value
p_value$Sad = Sad$p.value
p_value$Angry = Angry$p.value
p_value$Surprised = Surprised$p.value
p_value$Scared = Scared$p.value
p_value$Disgusted = Disgusted$p.value
p_value$Valence = Valence$p.value
p_value = as.data.frame(p_value)
row.names(p_value) = c("P-Value")
kable(p_value, caption = "t-test")
```

## Emotions Progression

```{r, echo= FALSE, message=FALSE, warning=FALSE, fig.width=8, fig.height=8}

library(tidyverse)
library(varhandle)
library(ggplot2)

neutral = c()
happy = c()
sad = c()
angry = c()
surprised = c()
scared = c()
disgusted = c()
valence = c()
emotions_progression_beliefs = c()
for(i in 1:30){
  x = mean((emotions_progression%>% filter(period == i))$neutral , na.rm = TRUE)
  neutral=rbind(neutral,x)
  x = mean((emotions_progression%>% filter(period == i))$happy , na.rm = TRUE)
  happy=rbind(happy,x)
  x = mean((emotions_progression%>% filter(period == i))$sad , na.rm = TRUE)
  sad=rbind(sad,x)
  x = mean((emotions_progression%>% filter(period == i))$angry , na.rm = TRUE)
  angry=rbind(angry,x)
  x = mean((emotions_progression%>% filter(period == i))$surprised , na.rm = TRUE)
  surprised=rbind(surprised,x)
  x = mean((emotions_progression%>% filter(period == i))$scared , na.rm = TRUE)
  scared=rbind(scared,x)
  x = mean((emotions_progression%>% filter(period == i))$disgusted , na.rm = TRUE)
  disgusted=rbind(disgusted,x)
  x = mean((emotions_progression%>% filter(period == i))$valence , na.rm = TRUE)
  valence=rbind(valence,x)
}
period = t(t(c(1:30)))
emotions_progression_beliefs = cbind(emotions_progression_beliefs,period)
emotions_progression_beliefs = cbind(emotions_progression_beliefs,neutral)
emotions_progression_beliefs = cbind(emotions_progression_beliefs,happy)
emotions_progression_beliefs = cbind(emotions_progression_beliefs,sad)
emotions_progression_beliefs = cbind(emotions_progression_beliefs,angry)
emotions_progression_beliefs = cbind(emotions_progression_beliefs,surprised)
emotions_progression_beliefs = cbind(emotions_progression_beliefs,scared)
emotions_progression_beliefs = cbind(emotions_progression_beliefs,disgusted)
emotions_progression_beliefs = cbind(emotions_progression_beliefs,valence)
colnames(emotions_progression_beliefs)= c("period", "neutral", "happy", "sad", "angry", "surprised", "scared", "disgusted","valence")
emotions_progression_beliefs = as.data.frame(emotions_progression_beliefs)

#emotions progression S1_S6  
#all participants
emotions = emotions_progression_beliefs
par(mfrow=c(4,2))
a = c(1:30)
plot( emotions$neutral~a, type="o" ,bty="l", xlab="Period" , ylab="Degree of Emotion" ,
      col=rgb(1,0.2,0.2,0.7) , lwd=2, pch=19,ylim=c(min(emotions$neutral), max(emotions$neutral)), main= "Neutral")
plot( emotions$happy~a, type="o" ,bty="l", xlab="" , ylab="" ,
      col=rgb(1,0.2,0.2,0.7) , lwd=2, pch=19,ylim=c(min(emotions$happy), max(emotions$happy)), main= "Happy")
plot( emotions$sad~a, type="o" ,bty="l", xlab="" , ylab="" ,
      col=rgb(1,0.2,0.2,0.7) , lwd=2, pch=19,ylim=c(min(emotions$sad), max(emotions$sad)), main= "Sad")
plot( emotions$angry~a, type="o" ,bty="l", xlab="" , ylab="" ,
      col=rgb(1,0.2,0.2,0.7) , lwd=2, pch=19,ylim=c(min(emotions$angry), max(emotions$angry)), main= "Angry")
plot( emotions$surprised~a, type="o" ,bty="l", xlab="" , ylab="" ,
      col=rgb(1,0.2,0.2,0.7) , lwd=2, pch=19,ylim=c(min(emotions$surprised), max(emotions$surprised)), main= "Surprised")
plot( emotions$scared~a, type="o" ,bty="l", xlab="" , ylab="" ,
      col=rgb(1,0.2,0.2,0.7) , lwd=2, pch=19,ylim=c(min(emotions$scared), max(emotions$scared)), main= "Scared")
plot( emotions$disgusted~a, type="o" ,bty="l", xlab="" , ylab="" ,
      col=rgb(1,0.2,0.2,0.7) , lwd=2, pch=19,ylim=c(min(emotions$disgusted), max(emotions$disgusted)), main= "Disgusted")
plot( emotions$valence~a, type="o" ,bty="l", xlab="" , ylab="" ,
      col=rgb(1,0.2,0.2,0.7) , lwd=2, pch=19,ylim=c(min(emotions$valence), max(emotions$valence)),main= "Valence")
abline(a = 0, b = 0)
```