---
title: "Emotional State and Traders' Expectations in Asset Markets - Experimental Evidence"
author: "Afik, Lahav, Maymoni & Noussair"
output: html_document
---

**Update: 28/02/2021**

Fixed some bugs

**Update: 11/03/2020**

Added "Average prices and prior market emotions"

Added "Percision in beliefs as a function of subjects’ average emotions (in t-1 record stage)"

Added "Percision in beliefs as a function of subjects’ average emotions (in t belief stage)"

Added "b(t) - P(t-1)"



**Update: 10/26/2020**

Added "Average short turm belief and prior market emotions"

Updated "Ztree Summary" with 4 CDA sessions"

Added "CDA" section:

  1. Added "Emotions Summary"
  2. Added "Regressions - Period beliefs as a function of Period and Market trends (without emotions)"
  3. Added "Period beliefs as a function of Period and Market trends (with record stage emotions of t-1)"

**Update: 06/21/2020**

Edited "Regressions - Period beliefs as a function of Period and Market trends (with emotions - same belief stage emotions)"

Added "Period beliefs as a function of Period and Market trends (with stage emotions of t-1)"

Added "Relationship between predicted and actual price change between periods t-1 and t - including record stage emotions of t-1"

**Update: 06/20/2020**

Added "Short term beliefs using record stage emotions of t-1"

Added "Long term beliefs using record stage emotions of t-1"

Added "b(t) - b(t-1) regression"

**Update: 10/22/2019**

Added "Relationship between predicted and actual price change between periods t-1 and t" to "Belief stage"

Added "Beliefs as a function of fundamental value" to "Belief stage"

**Update: 10/17/2019**

Added "Regressions - Upcoming period beliefs as a function of subjects' average emotions - percentage difference" to "Belief stage"

Added "Regressions - Percision in beliefs as a function of subjects' average emotions" to "Belief stage"

Added "Emotions Summary" to "Record stage"

Added "Regressions - Percision in beliefs as a function of subjects' average emotions" to "Record stage"

Added "Regressions - Total dividends received as a function of subjects' average emotions (traders only)" to "Record stage"

Added "Regression - Protfolio value as a function of subjects' average emotions (Traders only)" to "Record stage"

**Update: 10/16/2019**

Added "Regressions - Period beliefs as a function of subjects' average emotions".

Changed site layout.

**Update: 10/15/2019**

Fixed code error.


**Update: 07/31/2019**

Fixed "Periodtrend" and "Markettrend" variables.


**Update: 07/11/2019**

Added "Upcoming period beliefs as a function of subjects' average emotions" to "Regressions Summary".


**Update: 07/06/2019**

Added sessions analysis to "Emotions Summary", include "Peak price period" to graphs.

Added "Difference Between Markets" to "Emotions Summary".


**Update: 07/02/2019 - B**

"Regressions - Period and Market trends (witht emotions)" added.

Fixed stars cutoff in "Regressions - Period and Market trends (without emotions)"



**Update: 07/02/2019 - A**

"Emotions Summary" added.



**Update: 07/01/2019**

"Regressions - Period and Market trends (without emotions)" added.