---
title: "Protfolio value as a function of subjects' average emotions (Traders only)"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
---
$Y_{i,t} = C_{i} + \beta_1Neutrality_{i,t} + \beta_2Happiness_{i,t} + \beta_3Sadness_{i,t} + \beta_4Anger_{i,t} + \beta_5Surprise_{i,t} + \beta_6Fear_{i,t} + \beta_7Disgust_{i,t}$
(Fixed effects regression model)

$Y_{i,t} = Shares_{i,t} * Price_t$ 

# All sessions – combined

```{r, echo= FALSE, message=FALSE, warning=FALSE}
library(plm)
library(jtools)
library(huxtable)
library(tidyverse)

mydata <- read.csv(file="C:/Users/Liran/Google Drive/Study/PhD/Face_Reader/The_Experiment/portfolio_value/protfolio_value_record_stage.csv", header=TRUE, sep=",")

market1 = subset(mydata, period<=15)
market2 = subset(mydata, period>15)
#Fix effect market 1
Fixed_effects1 = plm(protfolio_value ~ neutral + happy + sad + angry + surprised + scared + disgusted, data=market1, index = c("id","period") , model="within")
#Fix effect market 2
Fixed_effects2 = plm(protfolio_value ~ neutral + happy + sad + angry + surprised + scared + disgusted, data=market2, index = c("id","period") , model="within")

export_summs(Fixed_effects1, Fixed_effects2,scale = TRUE,digits = 3,
             model.names = c("Market1", "Market2"),statistics = c(N = "nobs",Adj_R2 = "adj.r.squared", R2 = "r.squared") , coefs =  c("Neutrality" = "neutral" , "Happiness" = "happy", "Sadness" = "sad", "Anger" = "angry","Surprise" = "surprised", "Fear" = "scared", "Disgust" = "disgusted" ),error_format = "({p.value})", stars = c(`***` = 0.01, `**` = 0.05, `*` = 0.1))

```


# Session 1 

```{r, echo= FALSE, message=FALSE, warning=FALSE}
market1 = subset(mydata, period<=15)
market2 = subset(mydata, period>15)
market1 = subset(market1, s_num == "S1")
market2 = subset(market2, s_num == "S1")

#Fix effect market 1
Fixed_effects1 = plm(protfolio_value ~ neutral + happy + sad + angry + surprised + scared + disgusted, data=market1, index = c("id","period") , model="within")
#Fix effect market 2
Fixed_effects2 = plm(protfolio_value ~ neutral + happy + sad + angry + surprised + scared + disgusted, data=market2, index = c("id","period") , model="within")

export_summs(Fixed_effects1, Fixed_effects2,scale = TRUE,digits = 3,
             model.names = c("Market1", "Market2"),statistics = c(N = "nobs",Adj_R2 = "adj.r.squared", R2 = "r.squared") , coefs =  c("Neutrality" = "neutral" , "Happiness" = "happy", "Sadness" = "sad", "Anger" = "angry","Surprise" = "surprised", "Fear" = "scared", "Disgust" = "disgusted" ),error_format = "({p.value})", stars = c(`***` = 0.01, `**` = 0.05, `*` = 0.1))
```

# Session 2 

```{r, echo= FALSE, message=FALSE, warning=FALSE}
market1 = subset(mydata, period<=15)
market2 = subset(mydata, period>15)
market1 = subset(market1, s_num == "S2")
market2 = subset(market2, s_num == "S2")

#Fix effect market 1
Fixed_effects1 = plm(protfolio_value ~ neutral + happy + sad + angry + surprised + scared + disgusted, data=market1, index = c("id","period") , model="within")
#Fix effect market 2
Fixed_effects2 = plm(protfolio_value ~ neutral + happy + sad + angry + surprised + scared + disgusted, data=market2, index = c("id","period") , model="within")

export_summs(Fixed_effects1, Fixed_effects2,scale = TRUE,digits = 3,
             model.names = c("Market1", "Market2"),statistics = c(N = "nobs",Adj_R2 = "adj.r.squared", R2 = "r.squared") , coefs =  c("Neutrality" = "neutral" , "Happiness" = "happy", "Sadness" = "sad", "Anger" = "angry","Surprise" = "surprised", "Fear" = "scared", "Disgust" = "disgusted" ),error_format = "({p.value})", stars = c(`***` = 0.01, `**` = 0.05, `*` = 0.1))
```

# Session 3 

```{r, echo= FALSE, message=FALSE, warning=FALSE}
market1 = subset(mydata, period<=15)
market2 = subset(mydata, period>15)
market1 = subset(market1, s_num == "S3")
market2 = subset(market2, s_num == "S3")

#Fix effect market 1
Fixed_effects1 = plm(protfolio_value ~ neutral + happy + sad + angry + surprised + scared + disgusted, data=market1, index = c("id","period") , model="within")
#Fix effect market 2
Fixed_effects2 = plm(protfolio_value ~ neutral + happy + sad + angry + surprised + scared + disgusted, data=market2, index = c("id","period") , model="within")

export_summs(Fixed_effects1, Fixed_effects2,scale = TRUE,digits = 3,
             model.names = c("Market1", "Market2"),statistics = c(N = "nobs",Adj_R2 = "adj.r.squared", R2 = "r.squared") , coefs =  c("Neutrality" = "neutral" , "Happiness" = "happy", "Sadness" = "sad", "Anger" = "angry","Surprise" = "surprised", "Fear" = "scared", "Disgust" = "disgusted" ),error_format = "({p.value})", stars = c(`***` = 0.01, `**` = 0.05, `*` = 0.1))
```

# Session 4 

```{r, echo= FALSE, message=FALSE, warning=FALSE}
market1 = subset(mydata, period<=15)
market2 = subset(mydata, period>15)
market1 = subset(market1, s_num == "S4")
market2 = subset(market2, s_num == "S4")

#Fix effect market 1
Fixed_effects1 = plm(protfolio_value ~ neutral + happy + sad + angry + surprised + scared + disgusted, data=market1, index = c("id","period") , model="within")
#Fix effect market 2
Fixed_effects2 = plm(protfolio_value ~ neutral + happy + sad + angry + surprised + scared + disgusted, data=market2, index = c("id","period") , model="within")

export_summs(Fixed_effects1, Fixed_effects2,scale = TRUE,digits = 3,
             model.names = c("Market1", "Market2"),statistics = c(N = "nobs",Adj_R2 = "adj.r.squared", R2 = "r.squared") , coefs =  c("Neutrality" = "neutral" , "Happiness" = "happy", "Sadness" = "sad", "Anger" = "angry","Surprise" = "surprised", "Fear" = "scared", "Disgust" = "disgusted" ),error_format = "({p.value})", stars = c(`***` = 0.01, `**` = 0.05, `*` = 0.1))
```

# Session 5

```{r, echo= FALSE, message=FALSE, warning=FALSE}
market1 = subset(mydata, period<=15)
market2 = subset(mydata, period>15)
market1 = subset(market1, s_num == "S5")
market2 = subset(market2, s_num == "S5")

#Fix effect market 1
Fixed_effects1 = plm(protfolio_value ~ neutral + happy + sad + angry + surprised + scared + disgusted, data=market1, index = c("id","period") , model="within")
#Fix effect market 2
Fixed_effects2 = plm(protfolio_value ~ neutral + happy + sad + angry + surprised + scared + disgusted, data=market2, index = c("id","period") , model="within")

export_summs(Fixed_effects1, Fixed_effects2,scale = TRUE,digits = 3,
             model.names = c("Market1", "Market2"),statistics = c(N = "nobs",Adj_R2 = "adj.r.squared", R2 = "r.squared") , coefs =  c("Neutrality" = "neutral" , "Happiness" = "happy", "Sadness" = "sad", "Anger" = "angry","Surprise" = "surprised", "Fear" = "scared", "Disgust" = "disgusted" ),error_format = "({p.value})", stars = c(`***` = 0.01, `**` = 0.05, `*` = 0.1))
```

# Session 6

```{r, echo= FALSE, message=FALSE, warning=FALSE}
market1 = subset(mydata, period<=15)
market2 = subset(mydata, period>15)
market1 = subset(market1, s_num == "S6")
market2 = subset(market2, s_num == "S6")

#Fix effect market 1
Fixed_effects1 = plm(protfolio_value ~ neutral + happy + sad + angry + surprised + scared + disgusted, data=market1, index = c("id","period") , model="within")
#Fix effect market 2
Fixed_effects2 = plm(protfolio_value ~ neutral + happy + sad + angry + surprised + scared + disgusted, data=market2, index = c("id","period") , model="within")

export_summs(Fixed_effects1, Fixed_effects2,scale = TRUE,digits = 3,
             model.names = c("Market1", "Market2"),statistics = c(N = "nobs",Adj_R2 = "adj.r.squared", R2 = "r.squared") , coefs =  c("Neutrality" = "neutral" , "Happiness" = "happy", "Sadness" = "sad", "Anger" = "angry","Surprise" = "surprised", "Fear" = "scared", "Disgust" = "disgusted" ),error_format = "({p.value})", stars = c(`***` = 0.01, `**` = 0.05, `*` = 0.1))
```